%analyze data generated by runMagnEst.m experiment
%Created: 7/9/15, by Graczyk

clear all
close all

%set up directories
defaultdir=cd;
datafiles={};
datadir='C:\Users\Emily\Documents\MATLAB\JND Intensity\PerceivedMagnitude';
cd(datadir)
[datafiles,pathName]=uigetfile('.mat','Please select the file containing the data you wish to analyze','Multiselect','on');
cd(pathName)

outdir=pathName(1:end-5);
q=1;
f=figure;
h1=subplot(2,2,1);
h2=subplot(2,2,2);
h3=subplot(2,2,3);
h4=subplot(2,2,4);
col=[1 0.647059 0; 0.12549 0.698039 0.666667;0.690196 0.188235 0.376471;0 0 1];

%this will loop through all the data files
w=1;
for k=1:length(datafiles)
    load(datafiles{k}); %load data
    %get basic info from the file
    SID=MyData.PatientID;
    elec=cell2mat(MyData.Contact);
    expdate=datestr(datevec(MyData.DateVal),'yyyymmdd');
    expname=['Exp' datestr(datevec(datafiles{k}(11:end-4),'yyyy-mm-dd T HH.MM.SSPM'),'yyyymmddHHMMSS')];
    
    
    %arrange relevant data into a single matrix
    n=length(MyData.Response);
    %normalize data - normalize for each block of data
    br_pts=[0 68 135 203 270]; %trials after which a break was taken
    resp=[];
    for j=2:length(br_pts)
        if br_pts(j)<n
            setmax(j-1)=max(MyData.Response(br_pts(j-1)+1:br_pts(j)));
            resp(br_pts(j-1)+1:br_pts(j))=(MyData.Response(br_pts(j-1)+1:br_pts(j))/setmax(j-1))*100;
        elseif br_pts(j)==n
            setmax(j-1)=max(MyData.Response(br_pts(j-1)+1:n));
            resp(br_pts(j-1)+1:n)=(MyData.Response(br_pts(j-1)+1:n)/setmax(j-1))*100;
        else
        end
    end
    
    expdata=[];
    expdata=[MyData.ConditionList(1:n)' MyData.UpperFreq(1:n) MyData.UpperPW(1:n) MyData.UpperPA(1:n) MyData.Response];
    expdata=expdata(MyData.Trial(1):end,:);
    
    %save to alldata
    alldata.(expname).SID=SID;
    alldata.(expname).date=expdate;
    alldata.(expname).contact=elec;
    alldata.(expname).rawdata.header={'Condition', 'UpperFreq','UpperPW','UpperPA','Response'};
    alldata.(expname).rawdata.data=expdata;
    
    %save normalized data and overwrite the nonnormalized values in expdata
    expdata(:,5)=resp(MyData.Trial(1):end);
    alldata.(expname).normdata.setmax=setmax;
    alldata.(expname).normdata.header={'Condition', 'UpperFreq','UpperPW','UpperPA','NormalizedResponse'};
    alldata.(expname).normdata.data=expdata;
    
 
    sortdata=sortrows(expdata,[1 2 3]);
    
    ind_cond1=find(sortdata(:,1)==1);
    ind_cond2=find(sortdata(:,1)==2);
    ind_cond3=find(sortdata(:,1)==3);
    
    datacond1=sortdata(ind_cond1,:);
    datacond2=sortdata(ind_cond2,:);
    datacond3=sortdata(ind_cond3,:);
   
    
    sorted.datacond1=datacond1;
    sorted.datacond2=datacond2;
    sorted.datacond3=datacond3;
    for i=1:3
        
        %find rows where the stim parameters change
        if i==2
            ind_delta=find((sorted.(['datacond' num2str(i)])(2:end,2)-sorted.(['datacond' num2str(i)])(1:end-1,2))>0);
        else
            ind_delta=find((sorted.(['datacond' num2str(i)])(2:end,3)-sorted.(['datacond' num2str(i)])(1:end-1,3))>0);
            
        end
        ind_delta=cat(1,0,ind_delta);
        %iterate through each of the rows identified above, calculate means
        %and standard deviations and save to avgs
        for j=2:length(ind_delta)+1
            if j==length(ind_delta)+1
               
                %freq
                avgs.(['cond' num2str(i)])(j-1,1)=sorted.(['datacond' num2str(i)])(end,2);
                %pw
                avgs.(['cond' num2str(i)])(j-1,2)=sorted.(['datacond' num2str(i)])(end,3);
                %average of perceived magnitude values
                avgs.(['cond' num2str(i)])(j-1,3)=mean(sorted.(['datacond' num2str(i)])(ind_delta(j-1)+1:end,5));
                %standard error of the mean
                avgs.(['cond' num2str(i)])(j-1,4)=std(sorted.(['datacond' num2str(i)])(ind_delta(j-1)+1:end,5))/sqrt((ind_delta(end)-ind_delta(j-1)+1));
                
            else
                               end
                %freq
                avgs.(['cond' num2str(i)])(j-1,1)=sorted.(['datacond' num2str(i)])(ind_delta(j),2);
                %pw
                avgs.(['cond' num2str(i)])(j-1,2)=sorted.(['datacond' num2str(i)])(ind_delta(j),3);
                avgs.(['cond' num2str(i)])(j-1,3)=mean(sorted.(['datacond' num2str(i)])(ind_delta(j-1)+1:ind_delta(j),5));
                avgs.(['cond' num2str(i)])(j-1,4)=std(sorted.(['datacond' num2str(i)])(ind_delta(j-1)+1:ind_delta(j),5))/sqrt((ind_delta(j)-ind_delta(j-1)+1));
                
            end
        end
        %         f=figure;
        %         hold on
        %         if i==2
        %             scatter(sorted.datacond2(:,2),log(sorted.datacond2(:,5)))
        %             errorbar(avgs.(['cond' num2str(i)])(:,1),avgs.(['cond' num2str(i)])(:,3), avgs.(['cond' num2str(i)])(:,4),'o','Color','r','LineWidth',2);
        %             title(['S' SID ' M' elec ' Condition 2 - PW constant, freq variable'],'FontSize',14)
        %             xlabel('Frequency (Hz)','FontSize',14)
        %         else
        %             scatter(sorted.(['datacond' num2str(i)])(:,3),log(sorted.(['datacond' num2str(i)])(:,5)))
        %             errorbar(avgs.(['cond' num2str(i)])(:,2),avgs.(['cond' num2str(i)])(:,3), avgs.(['cond' num2str(i)])(:,4),'o','Color','r','LineWidth',2);
        %             xlabel('PW (us)','FontSize',14)
        %             if i==1
        %                 title(['S' SID ' M' elec ' Condition 1 - PW variable, freq constant'],'FontSize',14)
        %             else
        %                 title(['S' SID ' M' elec ' Condition 3 - both PW and freq variable'],'FontSize',14)
        %             end
        %         end
        %
        %
        %         ylabel('Perceived magnitude','FontSize',14)
        %         hold off
        %         cd([outdir '\Figures'])
        %         saveas(f,['S' SID 'M' elec 'cond' num2str(i) '.tif'])
        cd(pathName)
        
        m=size(avgs.(['cond' num2str(i)]),1);
        summdata(q:q+m-1,1)=str2num(SID);
        summdata(q:q+m-1,2)=str2num(elec);
        summdata(q:q+m-1,3)=i;
        summdata(q:q+m-1,4:7)=avgs.(['cond' num2str(i)]);
        q=q+m;
    end
    
    alldata.(expname).avgs=avgs;
    
    %% Fit power function
    %y=cx^b + a
    
    p=zeros(1,4);
    R2=0;
    
    for i=1:3
        ydataraw=alldata.(expname).avgs.(['cond' num2str(i)])(:,3);
        ydata=ydataraw-ydataraw(1);
        xdataf=alldata.(expname).avgs.(['cond' num2str(i)])(:,1);
        xdatapw=alldata.(expname).avgs.(['cond' num2str(i)])(:,2);
        %conditions 1 and 3 - fit models with PW varying
        if i==1 %|| i==3 %pw
            xdata=xdatapw-xdatapw(1);
            runs=1;
        elseif i==2
            xdata=xdataf-xdataf(1);
            runs=1;
        elseif i==3
            xdata=xdatapw-xdatapw(1);
            runs=2;
        end
        for s=1:runs
            if s==2
                xdata=xdataf-xdataf(1);
            end
            MSE=inf;
            p=[];
            for t=1:30
                try
                    th1=rand()*100-90; %y int
                    th2=rand()*50; %coeff
                    th3=rand(); %power
                    th4=rand()*10; %x offset
                    
                    thIN=[th1 th2 th3 th4]; %vector of theta estimates, to put in lsqcurvefit
                    lb=[-300 0 0 -200];
                    ub=[inf inf inf 10];
                    
                    F=@(p,xdata) (p(1)+ (p(2).*(xdata-p(4)).^p(3)).*heaviside(xdata-p(4)));
                    options=optimoptions(@lsqcurvefit,'MaxIter',1000);
                    [thOUT,resnorm,residual,flag]=lsqcurvefit(F,thIN,xdata,ydata,lb,ub,options);
                    %                     fitmdl=NonLinearModel.fit(xdata,ydata,F,thIN);
                    if mean(residual)< MSE;
                        p=thOUT;
                        MSE=mean(residual);
                        exitflag=flag;
%                         alldata.(expname).mdl.(['cond' num2str(i)]).PWdata.ydata=ydata+ydataraw(1);
%                         alldata.(expname).mdl.(['cond' num2str(i)]).PWdata.xdata=xdata+xdatapw(1);
                    end
                catch
                end
                
            end
            summary_data(w,1)=str2num(SID);
            summary_data(w,2)=str2num(expdate);
            summary_data(w,3)=str2num(elec);
            %     summary_data(w,4)=str2num(datestr(datevec(datafiles{k}(11:end-4),'yyyy-mm-dd T HH.MM.SSPM'),'yyyymmddHHMMSS'));
            summary_data(w,5)=i;
            summary_data(w,6)=2; %fit model with PW
            
            summary_data(w,7:10)=p';
            summary_data(w,12)=MSE;
            summary_data(w,13)=exitflag;
            %calculating Rsquared
            ybar=mean(ydata);
            fi=(p(1)+ (p(2).*(xdata-p(4)).^p(3)).*heaviside(xdata-p(4)));
            SStot=sum((ydata-ybar).^2);
            SSres=sum((ydata-fi).^2);
            R2=1-(SSres/SStot);
            summary_data(w,11)=R2;
            %iterate through summary_data
            w=w+1;
            
            %Plotting
            figure
            hold on
            xfit=[0:0.01:300];
            %add back in values
            p(1)=p(1)+ydataraw(1);
            if i==2 || s==2
                p(4)=p(4)+xdataf(1);
                scatter(xdata+xdataf(1),ydata+ydataraw(1))
                xlabel('Frequency (Hz)')
            else
                p(4)=p(4)+xdatapw(1);
                scatter(xdata+xdatapw(1),ydata+ydataraw(1))
                xlabel('PW (\mus)')
            end
            yfit=(p(1)+ (p(2).*(xfit-p(4)).^p(3)).*heaviside(xfit-p(4)));
            
            
            %             errorbar(avgs.(['cond' num2str(i)])(:,2),avgs.(['cond' num2str(i)])(:,3), avgs.(['cond' num2str(i)])(:,4),'o','Color','r','LineWidth',2);
            plot(xfit,yfit)
            text(200,50,['Rsq=' num2str(R2)]);
            title([SID ' M' elec ' cond' num2str(i)])
            axis([0 300 0 100])
            
            ylabel('Perceived magnitude (%)')
            hold off
        end
    end
    
    
end

cd(outdir)
save(['Analysis' datestr(now,'yyyymmddHHMMSS') '.mat'],'alldata')
cd(defaultdir)